//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentEmissaryData
    {
        public override long ID { get; set; }
        public override string Domain_ID { get; set; }
        public override string Name { get; set; }
        public override Nullable<bool> Admin { get; set; }
        public override Nullable<bool> Ambassador { get; set; }
    }
}
