//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentProjectNote
    {
        public long Project_ID { get; set; }
        public override string Note { get; set; }
        public string Employee_ID { get; set; }
        public override System.DateTime Date { get; set; }
    }
}
