//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmissaryRevision
    {
        public long EmissaryRevision_ID { get; set; }
        public long Revision_ID { get; set; }
        public long Emissary_ID { get; set; }
    
        public virtual Emissary Emissary { get; set; }
        public virtual EmissaryDomainID EmissaryDomainID { get; set; }
        public virtual EmissaryName EmissaryName { get; set; }
        public virtual Revision Revision { get; set; }
        public virtual EmissaryAdmin EmissaryAdmin { get; set; }
        public virtual EmissaryAmbassador EmissaryAmbassador { get; set; }
    }
}
