//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectRevisions = new HashSet<ProjectRevision>();
            this.EmissaryProjects = new HashSet<EmissaryProject>();
            this.SchoolProjects = new HashSet<SchoolProject>();
        }
    
        public long Project_ID { get; set; }
    
        public virtual ICollection<ProjectRevision> ProjectRevisions { get; set; }
        public virtual ICollection<EmissaryProject> EmissaryProjects { get; set; }
        public virtual ICollection<SchoolProject> SchoolProjects { get; set; }
    }
}
