//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRevision
    {
        public ProjectRevision()
        {
            this.ProjectFiles = new HashSet<ProjectFile>();
        }
    
        public long ProjectRevision_ID { get; set; }
        public long Revision_ID { get; set; }
        public long Project_ID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectDescription ProjectDescription { get; set; }
        public virtual ICollection<ProjectFile> ProjectFiles { get; set; }
        public virtual Revision Revision { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ProjectSummary ProjectSummary { get; set; }
        public virtual ProjectTitle ProjectTitle { get; set; }
    }
}
