//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public Revision()
        {
            this.EmissaryRevisions = new HashSet<EmissaryRevision>();
            this.EmissarySchools = new HashSet<EmissarySchool>();
            this.ProjectRevisions = new HashSet<ProjectRevision>();
            this.SchoolRevisions = new HashSet<SchoolRevision>();
            this.EmissaryProjects = new HashSet<EmissaryProject>();
            this.SchoolProjects = new HashSet<SchoolProject>();
        }
    
        public long Revision_ID { get; set; }
        public string Employee_ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<EmissaryRevision> EmissaryRevisions { get; set; }
        public virtual ICollection<EmissarySchool> EmissarySchools { get; set; }
        public virtual ICollection<ProjectRevision> ProjectRevisions { get; set; }
        public virtual RevisionNote RevisionNote { get; set; }
        public virtual ICollection<SchoolRevision> SchoolRevisions { get; set; }
        public virtual ICollection<EmissaryProject> EmissaryProjects { get; set; }
        public virtual ICollection<SchoolProject> SchoolProjects { get; set; }
    }
}
