//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.EmissarySchools = new HashSet<EmissarySchool>();
            this.SchoolRevisions = new HashSet<SchoolRevision>();
            this.SchoolProjects = new HashSet<SchoolProject>();
        }
    
        public long School_ID { get; set; }
    
        public virtual ICollection<EmissarySchool> EmissarySchools { get; set; }
        public virtual ICollection<SchoolRevision> SchoolRevisions { get; set; }
        public virtual ICollection<SchoolProject> SchoolProjects { get; set; }
    }
}
