//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaEngineAuth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolRevision
    {
        public long SchoolRevision_ID { get; set; }
        public long Revision_ID { get; set; }
        public long School_ID { get; set; }
    
        public virtual Revision Revision { get; set; }
        public virtual School School { get; set; }
        public virtual SchoolContactEmail SchoolContactEmail { get; set; }
        public virtual SchoolContactName SchoolContactName { get; set; }
        public virtual SchoolContactPhoneNumber SchoolContactPhoneNumber { get; set; }
        public virtual SchoolName SchoolName { get; set; }
    }
}
